# Generated by Django 3.1 on 2020-08-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mathematics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=1)),
                ('marks', models.IntegerField(default=0)),
                ('difficulty_level', models.CharField(blank=True, max_length=1)),
            ],
        ),
    ]
